"""empty message

Revision ID: 1da47bc29ed
Revises: 586ad3e896c
Create Date: 2015-06-03 13:56:28.848425

"""

# revision identifiers, used by Alembic.
revision = '1da47bc29ed'
down_revision = '586ad3e896c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_user_email', 'user', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_email', table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
