"""empty message

Revision ID: 3d6cd61be08
Revises: b55a4da25a
Create Date: 2015-06-14 17:30:13.461083

"""

# revision identifiers, used by Alembic.
revision = '3d6cd61be08'
down_revision = 'b55a4da25a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_claim_page_id_user_id', 'claim', ['page_id', 'user_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_claim_page_id_user_id', table_name='claim')
    ### end Alembic commands ###
