"""empty message

Revision ID: 49a31a27858
Revises: 1da47bc29ed
Create Date: 2015-06-06 20:25:05.793526

"""

# revision identifiers, used by Alembic.
revision = '49a31a27858'
down_revision = '1da47bc29ed'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pledge',
    sa.Column('pledge_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('page_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.page_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('pledge_id')
    )
    op.create_index('idx_page_url', 'page', ['url'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_page_url', table_name='page')
    op.drop_table('pledge')
    ### end Alembic commands ###
