"""empty message

Revision ID: 52a49ae1d8b
Revises: 3d6cd61be08
Create Date: 2015-08-15 18:52:33.828203

"""

# revision identifiers, used by Alembic.
revision = '52a49ae1d8b'
down_revision = '3d6cd61be08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=256), nullable=True))
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    op.drop_column('user', 'confirmed_at')
    op.drop_column('user', 'active')
    ### end Alembic commands ###
