from uuid import UUID
from flask_security import Security
from flask_security.datastore import SQLAlchemyDatastore, UserDatastore
from flask_security.forms import RegisterForm
from wtforms import StringField
from wtforms.validators import Required, Length, Regexp
from icoin import app
from .model import User
from .db import db
from .config import DefaultConfig
 

security = Security()

def init():
    app.config['SECURITY_REGISTERABLE'] = True
    app.config['SECURITY_PASSWORD_HASH'] = "bcrypt"
    if 'SECURITY_PASSWORD_SALT' not in app.config:
        # If the salt changes then all passwords are invalidated
        # so keep it static when SECRET_KEY is autogenerated
        if app.config['SECRET_KEY'] == DefaultConfig.SECRET_KEY:
            salt = b"icoin"
        else:
            salt = app.config['SECRET_KEY']
        app.config['SECURITY_PASSWORD_SALT'] = salt

    security.init_app(app, IcoinUserDatastore(),
            register_form=IcoinRegisterForm)


class IcoinUserDatastore(SQLAlchemyDatastore, UserDatastore):
    
    def __init__(self):
        SQLAlchemyDatastore.__init__(self, db)
        UserDatastore.__init__(self, User, None)

    def get_user(self, identifier):
        if isinstance(identifier, UUID):
            user = db.session.query(User).get(identifier)
        else:
            user = db.session.query(User).filter_by(email=identifier).first()
        return user

    def find_user(self, **kwargs):
        if "id" in kwargs:
            kwargs["user_id"] = kwargs["id"]
            del kwargs["id"]
        user = db.session.query(User).filter_by(**kwargs).first()
        return user

    def find_role(self, role):
        return None

class IcoinRegisterForm(RegisterForm):
    name = StringField('Name', validators=[Required(), Length(1, 64), 
            Regexp(r'^[A-Za-z0-9_\- ]+$', 0, 'Name must have only letters, numbers, spaces, dots, dashes or underscores')])

